### ISSUE TITLE
First animate in doesnt run

### ISSUE THREAD

**Issue by RealOrangeOne** [maxs15/react-native-modalbox#39]
When the modal is displayed for the first time between app load, the modal doesn't slide up. The background fade works fine, but not the slide in. Once the modal is closed, the animations then work fine, until the app is reloaded. 

I tried to hack around this, by toggling on load, but i gave up and wrote an issue instead :+1: 

Using React Native `0.19.0`

**Comment by MacKentoch** [comment]
Hi @maxs15 , 

Thank you for this useful modal (easier and faster than implementing our own one with a navigator).
I had the same problem as @RealOrangeOne .

As far as I identified the problem it seems linked to `this.stopAnimateClose();`.

At View first load it prevents modal from showing like it were interrupted...

Let me show you a little fix I applied in my application (*not optimal but fixes modal appearing on View first load*) : 
```javascript 
  /*
   * Event called when the container view layout is calculated
   */
  onContainerLayout: function(evt) {
   
     // => I commented all this code (I did fast like a bulldozer fix sorry...)
      // Checking if a animation was in progress
      // if (this.state.isAnimateOpen) {
      //   position = modalPosition;
      //   this.stopAnimateOpen();
      // } else if (this.state.isAnimateClose) {
      //   position = this.state.containerHeight;
      //   this.stopAnimateClose();
      // }
      
    // => I just leaved position
      position = modalPosition;   

```

I can see modal even at first View load (*but sometimes without being animated but not a priority for my application until a real fix*).

I hope it will help.

**Comment by maxs15** [comment]
Thanks for the example, I will check that

**Comment by maxs15** [comment]
The issue should be fixed in the last version ([1.2.9](https://github.com/maxs15/react-native-modalbox/releases/tag/v1.2.9))
Check it out ;)

**Comment by MacKentoch** [comment]
I'm afraid it still occurs.

But I think I found why it does occur.
I may submit a PR soon to give an hand (*I like this component* :+1:)

**Comment by maxs15** [comment]
Arf, I finally found the issue @MacKentoch, it was working on my side because there was one exception where my fix wasn't working: when the modal width/height is not equal to the window width/height on start up.
I'm going to push the new fix ! :)
You found the condition that caused the issue on your PR but it introduced some new issues with device rotations.

**Comment by maxs15** [comment]
Check the new version 1.3.0 and let me know

**Comment by MacKentoch** [comment]
@maxs15 yes! 
It is now fixed with v1.3.0

Thank you :+1:

**Comment by RealOrangeOne** [comment]
I too can confirm this works. Hoorah!! :smiley:
